### ISSUE TITLE
Doesn't prevent form submission if content is entered

### ISSUE THREAD

**Issue by jaasum** [craftcms/contact-form-honeypot#1]
In testing this it seems to make no difference if the form field has a value or not, the contact form will submit as normal. 

I made sure the Contact Form and Contact Form Honeypot plugins are both installed, I copy/pasted the Honey Pot field name into my template code, and I've tested both with display: none and having the form visible. If I give the Honey Pot field a value the contact form submits as normal.

Here is my contact form code.

```
<form class="form" method="post" action="" accept-charset="UTF-8">

        {% macro errorList(errors) %}
            {% if errors %}
                <ul class="errors">
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endmacro %}

        {% from _self import errorList %}

        {{ csrfInput() }}

        <input type="hidden" name="action" value="contact-form/send">
        {{ redirectInput('contact') }}

        <!-- This field confuses most spam bots. The form should only submit if it's left blank -->
        <div style="display: none"
          <label for="secretHoneypotParamName">Leave this field blank, it exists to fight spam.</label>
          <input id="secretHoneypotParamName" name="secretHoneypotParamName" type="text">
        </div>

        <fieldset>
          <div class="form-x-inline">
            <div class="form-x-field">
              <label for="name" class="visuallyhidden">Name</label>
              <input type="text" id="name" name="fromName" required="required" placeholder="Name" value="{{ message.fromName ?? '' }}">
              {{ message is defined and message ? errorList(message.getErrors('fromName')) }}
            </div>
            <div class="form-x-field">
              <label for="phone" class="visuallyhidden">Phone</label>
              <input type="tel" id="phone" name="message[phone]" required="required" placeholder="Phone" value="{{ message.message.phone ?? '' }}">
              {{ message is defined and message ? errorList(message.getErrors('message.phone')) }}
            </div>
            <div class="form-x-field">
              <label for="from" class="visuallyhidden">Email</label>
              <input type="email" id="from" name="fromEmail" required="required" placeholder="Email" value="{{ message.fromEmail ?? '' }}">
              {{ message is defined and message ? errorList(message.getErrors('fromEmail')) }}
            </div>
          </div>
        </fieldset>

        <fieldset>
          <div class="form-x-field">
            <label for="message" class="visuallyhidden">Message</label>
            <textarea id="message" name="message[body]" required="required" placeholder="Message &hellip;">{{ message.message.body ?? '' }}</textarea>
            {{ message is defined and message ? errorList(message.getErrors('message.body')) }}
          </div>
        </fieldset>

        <button class="button" type="submit">Send Message</button>

</form>
```

**Comment by tedbyron** [comment]
Seems like you have to handle this yourself, I ended up using something like this in JS
```js
document.getElementById('form').addEventListener('submit', function(event) {
  if (document.getElementById('honeypot-field').value !== '') {
    event.preventDefault();
  }
});
```

**Comment by tedbyron** [comment]
Actually not sure what the purpose of the plugin is then if it doesn't do this for you... 🤔

**Comment by brandonkelly** [comment]
Have you set the Honeypot Form Param setting in Settings → Plugins → Contact Form Honeypot → Settings ?

**Comment by jaasum** [comment]
Yes - and ensured it's an exact match with what is in my template.

**Comment by brandonkelly** [comment]
I can’t reproduce this - when the honeypot field is anythnig but an empty string, the email doesn’t actually get sent.

Are you sure that the email is actually getting sent? The expected behavior here is that Craft will _say_ that the email was sent successfully – but the email doesn’t actually get sent behind the scenes.

**Comment by jaasum** [comment]
Yes the email is getting sent. This is in a local environment.

**Comment by brandonkelly** [comment]
If you have Xdebug setup, can you put a breakpoint on line 36 of `vendor/craftcms/contact-form-honeypot/src/Plugin.php`:

https://github.com/craftcms/contact-form-honeypot/blob/d882f044275e99d95276a08424916af375b3b1bc/src/Plugin.php#L36

and then step through the code in that function to see which route it takes?

**Comment by jaasum** [comment]
Any alternatives to using xdebug? I'm not a php dev and am going down a rabbit hole of figuring out how to install xdebug, get php storm running, etc.

**Comment by jaasum** [comment]
I realized this was an error in my template code. I was missing a closing bracket, which made any value in the field moot apparently.

**Comment by brandonkelly** [comment]
Glad you got it sorted!
