### ISSUE TITLE
Submissions not being delivered - don't know where to start with reporting problems accurately

### ISSUE THREAD

**Issue by iparr** [craftcms/contact-form-honeypot#10]
I've had this working before on other projects, but not this time.

If I remove the line `<input id="beeUnit" name="beeUnit" type="text" class="u-visually-hidden">` from my form it works fine (lots of spam though!).

I have the following in my `contact-form-honeypot.php` file:
```
return [
    'honeypotParam' => 'beeUnit'
];
```

On submission, the form transitions to the 'thanks' page, but I don't see anything delivered.

I am using the `MailGun` plugin/service to handle my emails.

I have the same problem on my dev (MacOS, Vagrant) and my production (Ubuntu, LEMP) environments.

Don't know where to start debugging this. `web.log` _looks_ fine to me. Plugins are installed and working fine (i.e. I can visit their settings pages in the Dashboard).

### Additional info

- Craft version: 3.7.37 Pro
- PHP version: 7.4.27
- Database driver & version: MySQL 8.0.27 
- Plugins & versions: Latest available of both Contact Form (2.3.0) + Honeypot (1.0.2)

**Comment by tommysvr** [comment]
Hi @iparr, are you still having this issue? I couldn’t reproduce running the latest versions of Craft 3 + both plugins with ddev / MailHog.
