### ISSUE TITLE
Empty honeypot val

### ISSUE THREAD

**Issue by mikedaviesweb** [craftcms/contact-form-honeypot#2]
I've been having some issues with getting honeypot to work with my craft 3 contact form, I did some digging around and `$val = Craft::$app->getRequest()->getBodyParam($settings->honeypotParam);` appears to be returning empty, even when I am manually add text to the honeypot field. Any ideas on why this is happening? Thanks.

**Comment by angrybrad** [comment]
My guess is that the honeypot param name you entered in the plugin settings doesn't match the honeypot param name and id on the input field of your form.  I'd double check those: https://github.com/craftcms/contact-form-honeypot#setup
