### ISSUE TITLE
Extend for Guest Entries?

### ISSUE THREAD

**Issue by mikestecker** [craftcms/contact-form-honeypot#3]
Could this be extended to work with [Guest Entries](https://github.com/craftcms/guest-entries)?

**Comment by angrybrad** [comment]
Probably not this exact plugin, but you could do something similar in a Guest Entries Honeypot plugin.

**Comment by mikestecker** [comment]
Cool thanks @angrybrad. Would it be ok to fork this and make one?

**Comment by angrybrad** [comment]
Sure thing!
