### ISSUE TITLE
Honeypot config file

### ISSUE THREAD

**Issue by mortscode** [craftcms/contact-form-honeypot#4]
Is there a way to use a config file to setup the honeypot param?

The reason being that I have `allowAdminChanges => false` for my server.

This may already exist. Not seeing it on the readme.

**Comment by elodiegrondin** [comment]
@mortscode I think you can create a contact-form-honeypot.php in config folder.
```
<?php

return [
  'dev' => [
	  'honeypotParam' => 'value',
  ],
  'production' => [
	  'honeypotParam'=> 'value',
  ],
];
```

**Comment by mortscode** [comment]
This isn't working for me. The text in the field isn't changing to the value in that config file, or indicating that it's being defined by the config file.

**Comment by i-just** [comment]
@elodiegrondin’s response is correct. 

@mortscode The thing to note is that the text in the field shouldn’t change to the value in that config file. 
If you change`honeypotParam` parameter via the control panel or the config file, you still need to ensure that the input field’s name matches the value you provided. Via this parameter, you set the name of the honeypot field that the plugin should check against.

For example, if you set the `honeypotParam` to `myHP`, then you still need to add `<input id="myHP" name="myHP" type="text">` to the template (and hide it with CSS). If you were to change your `honeypotParam` to `myHP2` but leave the input field name as it was (with the name of `myHP`), the honeypot field wouldn’t be able to do its job (e.g. it would let through submissions that had the honeypot field populated with a value). 

If you correctly add the `honeypotParam` value via `contact-form-honeypot.php` in the config folder and then visit the control panel > settings > plugins > contact form honeypot page, you’ll see the message saying that it’s overwritten via the config file.

I hope this clears things up!
