### ISSUE TITLE
No Craft 3.4.1 compatibility?

### ISSUE THREAD

**Issue by klick** [craftcms/contact-form-honeypot#5]
Installation from the CLI fails with error:`*** failed to install contact-form-honeypot: No plugin exists with the handle "contact-form-honeypot"`.

Craft Version: 3.4.1

**Comment by klick** [comment]
Installation fails with error:
`*** failed to install contact-form-honeypot: No plugin exists with the handle "contact-form-honeypot".`

Craft Version: 3.4.1

**Comment by kevinmu17** [comment]
No issues here, i'm on Craft Pro 3.4.11.

What are you doing precisely to get this error?
